In [4]:
import requests
from pathlib import Path

r = requests.get(
    "https://cdn.lazarev.fun/data/"
    "const_vdv_pretty_with_mw_volume.tsv"
)

Path("data/const_vdv_pretty_with_mv_volume.tsv") \
    .write_text(r.content.decode("utf8"))

1541

In [5]:
import requests
from pathlib import Path

r = requests.get(
    "https://cdn.lazarev.fun/data/"
    "compounds.tsv"
)

Path("data/compounds.tsv") \
    .write_text(r.content.decode("utf8"))

1123823

In [9]:
import pandas as pd
compounds = pd.read_csv("data/compounds.tsv", sep="\t", index_col=0)
compounds.head(1)

,cid,elements,atoms,bonds,coordinate_type,charge,molecular_formula,molecular_weight,connectivity_smiles,smiles,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
0,947,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,0,N2,28.014,N#N,N#N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
compounds.molecular_formula[:10]

0     N2
1     N2
2     N2
3     N2
4    N2+
5     N2
6     N2
7     N2
8    H3N
9    H3N
Name: molecular_formula, dtype: object

In [ ]:
compounds.groupby("molecular_formula").

In [19]:
compounds.groupby("molecular_formula").first().head(1)

,cid,elements,atoms,bonds,coordinate_type,charge,molecular_weight,connectivity_smiles,smiles,inchi,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
molecular_formula,,,,,,,,,,,,,,,,,,,,,
Ar,23968,['Ar'],"[{'aid': 1, 'number': 18, 'element': 'Ar', 'x'...",[],2d,0,39.9,[Ar],[Ar],InChI=1S/Ar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
vdv_const = pd.read_csv("data/const_vdv_pretty_with_mv_volume.tsv", sep="\t")
vdv_const.set_index("Formula").head()

        Substance  Const_a  Const_b  Mol_weight     Volume
Formula
N2           Азот   0.1370     38.7      28.014   2.998428
NH3        Аммиак   0.4225     37.1      17.031   1.873579
Ar          Аргон   0.1355     32.0      39.900   4.988916
C2H2     Ацетилен   0.4516     52.2      26.040   3.001687
Br2          Бром   0.9750     59.1     159.810  14.476459

In [24]:
vdv_const_rich = vdv_const.set_index("Formula").join(
    compounds.groupby("molecular_formula").first(),
    how="inner"
)

vdv_const_rich.head()

,Substance,Const_a,Const_b,Mol_weight,Volume,cid,elements,atoms,bonds,coordinate_type,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
N2,Азот,0.1370,38.7,28.014,2.998428,947,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ar,Аргон,0.1355,32.0,39.900,4.988916,23968,['Ar'],"[{'aid': 1, 'number': 18, 'element': 'Ar', 'x'...",[],2d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C2H2,Ацетилен,0.4516,52.2,26.040,3.001687,6326,"['C', 'C', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}, {'aid1': ...",2d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Br2,Бром,0.9750,59.1,159.810,14.476459,24408,"['Br', 'Br']","[{'aid': 1, 'number': 35, 'element': 'Br', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C4H10,Бутан,1.3890,116.4,58.120,6.752104,7843,"['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', ...","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 1}, {'aid1': ...",2d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
vdv_const.shape, vdv_const_rich.shape

((30, 6), (22, 47))

In [31]:
set(vdv_const.Formula)

{'Ar',
 'Br2',
 'C2H2',
 'C2H4',
 'C2H6',
 'C3H8',
 'C4H10',
 'CH4',
 'CO',
 'CO2',
 'Cl2',
 'F2',
 'H2',
 'H2O',
 'H2S',
 'HBr',
 'HCN',
 'HCl',
 'HF',
 'He',
 'Kr',
 'N2',
 'N2H4',
 'NH3',
 'Ne',
 'O2',
 'O3',
 'SF6',
 'SO2',
 'Xe'}

In [32]:
set(vdv_const_rich.index)

{'Ar',
 'Br2',
 'C2H2',
 'C2H4',
 'C2H6',
 'C3H8',
 'C4H10',
 'CH4',
 'CO',
 'CO2',
 'Cl2',
 'F2',
 'H2',
 'H2O',
 'H2S',
 'He',
 'Kr',
 'N2',
 'Ne',
 'O2',
 'O3',
 'Xe'}

In [34]:
set(vdv_const.Formula) - set(vdv_const_rich.index)

{'HBr', 'HCN', 'HCl', 'HF', 'N2H4', 'NH3', 'SF6', 'SO2'}

In [42]:
compounds[compounds.molecular_formula.str.contains("Cl")]

,cid,elements,atoms,bonds,coordinate_type,charge,molecular_formula,molecular_weight,connectivity_smiles,smiles,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
515,24526,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,Cl2,70.900000,ClCl,ClCl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,5460592,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,1,Cl2+,70.900000,Cl[Cl+],Cl[Cl+],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,6857667,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,-1,Cl2-,70.900000,[Cl-]Cl,[Cl-]Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,11137084,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,Cl2,73.931805,ClCl,[37Cl][37Cl],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
519,21584072,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",[],2d,-2,Cl2-2,70.900000,[Cl-].[Cl-],[Cl-].[Cl-],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,9793690,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,Cl2,71.936614,ClCl,[36Cl][36Cl],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,24995198,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,Cl2,69.937705,ClCl,[35Cl][35Cl],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
522,313,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,36.460000,Cl,Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,522634,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,37.470000,Cl,[2H]Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
524,18348331,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",[],2d,0,ClH,36.460000,[H+].[Cl-],[H+].[Cl-],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525,123256,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,36.460000,Cl,[1H]Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,105062,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,36.976300,Cl,[36ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,167013,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,38.976000,Cl,[38ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,167304,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,39.976000,Cl,[39ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,15763865,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,37.973900,Cl,[37ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,44150317,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,35.976800,Cl,[35ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,59069996,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,38.470000,Cl,[3H]Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,10313041,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,34.981700,Cl,[34ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,86301162,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,32.993700,Cl,[32ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,86301163,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,33.985400,Cl,[33ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
535,101534066,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,36.982954,Cl,[2H][35Cl],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536,122198780,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",[],2d,0,ClH,36.460000,[H+].[Cl-],[1H+].[Cl-],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
%pip install chemparse

In [44]:
import chemparse

In [45]:
sorted(chemparse.parse_formula("HCl").items())

[('Cl', 1.0), ('H', 1.0)]

In [46]:
chemparse.parse_formula(compounds.molecular_formula)

{}

In [47]:
compounds.molecular_formula.map(chemparse.parse_formula)

0                          {'N': 2.0}
1                          {'N': 2.0}
2                          {'N': 2.0}
3                          {'N': 2.0}
4                {'N': 2.0, '+': 1.0}
                    ...
607              {'C': 2.0, 'H': 4.0}
608    {'C': 2.0, 'H': 4.0, '+': 1.0}
609    {'C': 2.0, 'H': 4.0, '+': 1.0}
610              {'C': 2.0, 'H': 4.0}
611              {'C': 2.0, 'H': 4.0}
Name: molecular_formula, Length: 612, dtype: object

In [48]:
compounds.molecular_formula.map(
    lambda f:
    tuple(sorted(chemparse.parse_formula(f).items()))
)

0                         ((N, 2.0),)
1                         ((N, 2.0),)
2                         ((N, 2.0),)
3                         ((N, 2.0),)
4                ((+, 1.0), (N, 2.0))
                    ...
607              ((C, 2.0), (H, 4.0))
608    ((+, 1.0), (C, 2.0), (H, 4.0))
609    ((+, 1.0), (C, 2.0), (H, 4.0))
610              ((C, 2.0), (H, 4.0))
611              ((C, 2.0), (H, 4.0))
Name: molecular_formula, Length: 612, dtype: object

In [51]:
def parse_molecular_formula(formula):
    return tuple(sorted(chemparse.parse_formula(formula).items()))


compounds["parsed_formula"] = compounds.molecular_formula.map(
    parse_molecular_formula
)
compounds.head(1)

,cid,elements,atoms,bonds,coordinate_type,charge,molecular_formula,molecular_weight,connectivity_smiles,smiles,...,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d,parsed_formula
0,947,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,0,N2,28.014,N#N,N#N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((N, 2.0),)"

In [53]:
vdv_const["parsed_formula"] = vdv_const.Formula.map(
    parse_molecular_formula
)
vdv_const.head(1)

  Substance Formula  Const_a  Const_b  Mol_weight    Volume parsed_formula
0      Азот      N2    0.137     38.7      28.014  2.998428    ((N, 2.0),)

In [54]:
vdv_const_rich = vdv_const.set_index("parsed_formula").join(
    compounds.groupby("parsed_formula").first(),
    how="inner"
)

vdv_const_rich.shape

(30, 49)

In [57]:
vdv_const_rich.head(1)

,Substance,Formula,Const_a,Const_b,Mol_weight,Volume,cid,elements,atoms,bonds,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
parsed_formula,,,,,,,,,,,,,,,,,,,,,
"((N, 2.0),)",Азот,N2,0.137,38.7,28.014,2.998428,947,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
vdv_const_features = vdv_const_rich[
  ["Formula", "Const_a", "Const_b", "Mol_weight", "Volume" , "bonds"]
]
vdv_const_features.set_index("Formula", inplace=True)
vdv_const_features.head(1)

,Const_a,Const_b,Mol_weight,Volume,bonds
Formula,,,,,
N2,0.137,38.7,28.014,2.998428,"[{'aid1': 1, 'aid2': 2, 'order': 3}]"

In [83]:
import json
vdv_const_features["n_bonds"] = vdv_const_features.bonds.map(
    lambda bonds: sum(
        b["order"] for b in json.loads(bonds.replace("'", '"'))
    )
)
vdv_const_features.head(1)

<ipython-input-83-c1accaf683e6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vdv_const_features["n_bonds"] = vdv_const_features.bonds.map(

,Const_a,Const_b,Mol_weight,Volume,bonds,n_bonds
Formula,,,,,,
N2,0.137,38.7,28.014,2.998428,"[{'aid1': 1, 'aid2': 2, 'order': 3}]",3

In [85]:
vdv_const_features = vdv_const_features.drop(columns=["bonds"])

In [86]:
vdv_const_features.head()

         Const_a  Const_b  Mol_weight     Volume  n_bonds
Formula
N2        0.1370     38.7      28.014   2.998428        3
NH3       0.4225     37.1      17.031   1.873579        3
Ar        0.1355     32.0      39.900   4.988916        0
C2H2      0.4516     52.2      26.040   3.001687        5
Br2       0.9750     59.1     159.810  14.476459        1

In [88]:
from sklearn.decomposition import PCA

In [97]:
pca = PCA(n_components=5)
pca.fit(vdv_const_features)
pca.explained_variance_ratio_

array([7.64589566e-01, 2.33328404e-01, 1.46498610e-03, 6.01380926e-04,
       1.56632094e-05])

In [96]:
pd.DataFrame(pca.components_)

          0         1         2         3         4
0  0.004248  0.247646  0.965517  0.079888  0.007009
1  0.011095  0.962324 -0.247067 -0.007580  0.112739
2 -0.007389 -0.111006  0.020263  0.012443  0.993508
3  0.034881 -0.011578 -0.079515  0.996085 -0.011888
4  0.999294 -0.012154  0.001564 -0.034932  0.006479