In [1]:
import requests
from pathlib import Path

vdv_consts_path = Path("/drive/data/const_vdv_pretty_with_mw_volume.tsv")
vdv_consts_path.write_text(
    requests.get(
        "https://cdn.lazarev.fun/data/"
        "const_vdv_pretty_with_mw_volume.tsv"
    ).content.decode("utf8")
)

1541

In [2]:
compounds_path = Path("/drive/data/compounds.tsv")
compounds_path.write_text(
    requests.get(
        "https://cdn.lazarev.fun/data/"
        "compounds.tsv"
    ).content.decode("utf8")
)

1123823

In [3]:
import pandas as pd
vdv_consts = pd.read_csv(vdv_consts_path, sep="\t")
vdv_consts.head(1)

  Substance Formula  Const_a  Const_b  Mol_weight    Volume
0      Азот      N2    0.137     38.7      28.014  2.998428

`compounds.tsv`

In [4]:
compounds = pd.read_csv(compounds_path, sep="\t", index_col=0)
compounds.head()

,cid,elements,atoms,bonds,coordinate_type,charge,molecular_formula,molecular_weight,connectivity_smiles,smiles,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
0,947,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,0,N2,28.014000,N#N,N#N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12195976,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,0,N2,27.013000,N#N,N#[13N],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,71309542,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,0,N2,28.010000,N#N,N#[14N],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10197604,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,0,N2,30.000218,N#N,[15N]#[15N],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5460618,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,1,N2+,28.014000,N#[N+],N#[N+],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
vdv_consts.join(
    compounds.set_index("molecular_formula"), 
    on="Formula",
    how="left",
)

,Substance,Formula,Const_a,Const_b,Mol_weight,Volume,cid,elements,atoms,bonds,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
0,Азот,N2,0.1370,38.7,28.014,2.998428,947.0,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Азот,N2,0.1370,38.7,28.014,2.998428,12195976.0,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Азот,N2,0.1370,38.7,28.014,2.998428,71309542.0,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Азот,N2,0.1370,38.7,28.014,2.998428,10197604.0,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Азот,N2,0.1370,38.7,28.014,2.998428,24985404.0,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,Этилен,C2H4,0.4612,58.2,28.050,3.251264,173207916.0,"['C', 'C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 2}, {'aid1': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Этилен,C2H4,0.4612,58.2,28.050,3.251264,58681544.0,"['C', 'C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 2}, {'aid1': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Этилен,C2H4,0.4612,58.2,28.050,3.251264,101089398.0,"['C', 'C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 2}, {'aid1': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Этилен,C2H4,0.4612,58.2,28.050,3.251264,102090023.0,"['C', 'C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 2}, {'aid1': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Этилен,C2H4,0.4612,58.2,28.050,3.251264,175586271.0,"['C', 'C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 2}, {'aid1': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
vdv_consts

             Substance Formula  Const_a  Const_b  Mol_weight     Volume
0                 Азот      N2  0.13700     38.7   28.014000   2.998428
1               Аммиак     NH3  0.42250     37.1   17.031000   1.873579
2                Аргон      Ar  0.13550     32.0   39.900000   4.988916
3             Ацетилен    C2H2  0.45160     52.2   26.040000   3.001687
4                 Бром     Br2  0.97500     59.1  159.810000  14.476459
5         Бромоводород     HBr  0.45000     44.2   80.910000   7.363018
6                Бутан   C4H10  1.38900    116.4   58.120000   6.752104
7                 Вода     H2O  0.55370     30.5   18.015000   1.453837
8              Водород      H2  0.02452     26.5    2.016000   0.249576
9     Гексафторид серы     SF6  0.78570     87.9  146.060000   9.503456
10               Гелий      He  0.00346     23.8    4.002600   0.091952
11            Гидразин    N2H4  0.84600     46.2   32.046000   3.497581
12            Кислород      O2  0.13820     31.9   31.999000   2.408521
13             Криптон      Kr  0.51930     10.6   83.800000   6.538266
14              Ксенон      Xe  0.41920     51.6  131.290000  11.494040
15               Метан     CH4  0.23030     43.1   16.043000   1.875208
16                Неон      Ne  0.02080     16.7   20.180000   0.817283
17                Озон      O3  0.35700     48.7   47.998000   3.612781
18      Окись углерода      CO  0.14720     39.5   28.010000   2.580316
19              Пропан    C3H8  0.93900     90.5   44.100000   5.126472
20  Сернистый ангидрид     SO2  0.68650     56.8   64.070000   7.257569
21         Сероводород     H2S  0.45440     43.4   34.080000   5.098625
22      Углекислый газ     CO2  0.36580     42.9   44.009000   3.784576
23                Фтор      F2  0.11710     29.0   37.996806   1.551469
24        Фтороводород      HF  0.95650     73.9   20.006400   0.900523
25                Хлор     Cl2  0.63430     54.2   70.900000   8.890355
26        Хлороводород     HCl  0.37000     40.6   36.460000   4.569966
27        Циановодород     HCN  1.12900     88.1   27.025000   3.000058
28                Этан    C2H6  0.55800     65.1   30.070000   3.500840
29              Этилен    C2H4  0.46120     58.2   28.050000   3.251264

In [7]:
vdv_consts_rich = vdv_consts.join(
    compounds.groupby("molecular_formula").first(), 
    on="Formula",
    how="left",
)
    
vdv_consts_rich.shape

(30, 48)

In [8]:
vdv_consts_rich.elements.unique().shape

(23,)

In [9]:
vdv_consts.Formula.unique().shape

(30,)

In [10]:
vdv_consts_rich = vdv_consts.join(
    compounds.groupby("molecular_formula").first(), 
    on="Formula",
    how="inner",
)
    
vdv_consts_rich.shape

(22, 48)

In [11]:
set(vdv_consts.Formula.unique()) - set(vdv_consts_rich.Formula.unique())

{'HBr', 'HCN', 'HCl', 'HF', 'N2H4', 'NH3', 'SF6', 'SO2'}

In [12]:
compounds[compounds.molecular_formula.str.contains("Cl")]

,cid,elements,atoms,bonds,coordinate_type,charge,molecular_formula,molecular_weight,connectivity_smiles,smiles,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
515,24526,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,Cl2,70.900000,ClCl,ClCl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,5460592,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,1,Cl2+,70.900000,Cl[Cl+],Cl[Cl+],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,6857667,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,-1,Cl2-,70.900000,[Cl-]Cl,[Cl-]Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,11137084,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,Cl2,73.931805,ClCl,[37Cl][37Cl],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
519,21584072,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",[],2d,-2,Cl2-2,70.900000,[Cl-].[Cl-],[Cl-].[Cl-],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,9793690,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,Cl2,71.936614,ClCl,[36Cl][36Cl],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,24995198,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,Cl2,69.937705,ClCl,[35Cl][35Cl],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
522,313,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,36.460000,Cl,Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,522634,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,37.470000,Cl,[2H]Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
524,18348331,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",[],2d,0,ClH,36.460000,[H+].[Cl-],[H+].[Cl-],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525,123256,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,36.460000,Cl,[1H]Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,105062,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,36.976300,Cl,[36ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,167013,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,38.976000,Cl,[38ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,167304,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,39.976000,Cl,[39ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,15763865,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,37.973900,Cl,[37ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,44150317,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,35.976800,Cl,[35ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,59069996,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,38.470000,Cl,[3H]Cl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,10313041,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,34.981700,Cl,[34ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,86301162,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,32.993700,Cl,[32ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,86301163,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,33.985400,Cl,[33ClH],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
535,101534066,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...","[{'aid1': 1, 'aid2': 2, 'order': 1}]",2d,0,ClH,36.982954,Cl,[2H][35Cl],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536,122198780,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",[],2d,0,ClH,36.460000,[H+].[Cl-],[1H+].[Cl-],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
compounds.head(1)

,cid,elements,atoms,bonds,coordinate_type,charge,molecular_formula,molecular_weight,connectivity_smiles,smiles,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
0,947,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...","[{'aid1': 1, 'aid2': 2, 'order': 3}]",2d,0,N2,28.014,N#N,N#N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
vdv_consts.head(1)

  Substance Formula  Const_a  Const_b  Mol_weight    Volume
0      Азот      N2    0.137     38.7      28.014  2.998428

In [15]:
vdv_consts_rich = vdv_consts.join(
    compounds.groupby("molecular_formula").first().set_index("molecular_weight"), 
    on="Mol_weight",
    how="left",
)
    
vdv_consts_rich.shape

(60, 47)

In [16]:
%pip install chemparse

In [17]:
import chemparse

def parse_formula(formula):
    return tuple(sorted(chemparse.parse_formula(formula).items()))

In [18]:
vdv_consts["Parsed_Formula"] = vdv_consts.Formula.map(parse_formula)
compounds["parsed_formula"] = compounds.molecular_formula.map(parse_formula)

vdv_consts_rich = vdv_consts.join(
    compounds.groupby("parsed_formula").first(), 
    on="Parsed_Formula",
    how="inner",
)
    
vdv_consts_rich.shape

(30, 50)

In [19]:
vdv_consts_rich

,Substance,Formula,Const_a,Const_b,Mol_weight,Volume,Parsed_Formula,cid,elements,atoms,...,multipoles_3d,conformer_rmsd_3d,effective_rotor_count_3d,pharmacophore_features_3d,mmff94_partial_charges_3d,mmff94_energy_3d,conformer_id_3d,shape_selfoverlap_3d,feature_selfoverlap_3d,shape_fingerprint_3d
0,Азот,N2,0.13700,38.7,28.014000,2.998428,"((N, 2.0),)",947,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Аммиак,NH3,0.42250,37.1,17.031000,1.873579,"((H, 3.0), (N, 1.0))",222,"['N', 'H', 'H', 'H']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Аргон,Ar,0.13550,32.0,39.900000,4.988916,"((Ar, 1.0),)",23968,['Ar'],"[{'aid': 1, 'number': 18, 'element': 'Ar', 'x'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ацетилен,C2H2,0.45160,52.2,26.040000,3.001687,"((C, 2.0), (H, 2.0))",6326,"['C', 'C', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Бром,Br2,0.97500,59.1,159.810000,14.476459,"((Br, 2.0),)",24408,"['Br', 'Br']","[{'aid': 1, 'number': 35, 'element': 'Br', 'x'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Бромоводород,HBr,0.45000,44.2,80.910000,7.363018,"((Br, 1.0), (H, 1.0))",260,"['Br', 'H']","[{'aid': 1, 'number': 35, 'element': 'Br', 'x'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Бутан,C4H10,1.38900,116.4,58.120000,6.752104,"((C, 4.0), (H, 10.0))",7843,"['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', ...","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Вода,H2O,0.55370,30.5,18.015000,1.453837,"((H, 2.0), (O, 1.0))",962,"['O', 'H', 'H']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Водород,H2,0.02452,26.5,2.016000,0.249576,"((H, 2.0),)",783,"['H', 'H']","[{'aid': 1, 'number': 1, 'element': 'H', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Гексафторид серы,SF6,0.78570,87.9,146.060000,9.503456,"((F, 6.0), (S, 1.0))",17358,"['S', 'F', 'F', 'F', 'F', 'F', 'F']","[{'aid': 1, 'number': 16, 'element': 'S', 'x':...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Гелий,He,0.00346,23.8,4.002600,0.091952,"((He, 1.0),)",23987,['He'],"[{'aid': 1, 'number': 2, 'element': 'He', 'x':...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Гидразин,N2H4,0.84600,46.2,32.046000,3.497581,"((H, 4.0), (N, 2.0))",9321,"['N', 'N', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Кислород,O2,0.13820,31.9,31.999000,2.408521,"((O, 2.0),)",977,"['O', 'O']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Криптон,Kr,0.51930,10.6,83.800000,6.538266,"((Kr, 1.0),)",66380,['Kr'],"[{'aid': 1, 'number': 36, 'element': 'Kr', 'x'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Ксенон,Xe,0.41920,51.6,131.290000,11.494040,"((Xe, 1.0),)",23991,['Xe'],"[{'aid': 1, 'number': 54, 'element': 'Xe', 'x'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Метан,CH4,0.23030,43.1,16.043000,1.875208,"((C, 1.0), (H, 4.0))",297,"['C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Неон,Ne,0.02080,16.7,20.180000,0.817283,"((Ne, 1.0),)",23935,['Ne'],"[{'aid': 1, 'number': 10, 'element': 'Ne', 'x'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Озон,O3,0.35700,48.7,47.998000,3.612781,"((O, 3.0),)",24823,"['O', 'O', 'O']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Окись углерода,CO,0.14720,39.5,28.010000,2.580316,"((C, 1.0), (O, 1.0))",281,"['O', 'C']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Пропан,C3H8,0.93900,90.5,44.100000,5.126472,"((C, 3.0), (H, 8.0))",6334,"['C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', ...","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Сернистый ангидрид,SO2,0.68650,56.8,64.070000,7.257569,"((O, 2.0), (S, 1.0))",1119,"['S', 'O', 'O']","[{'aid': 1, 'number': 16, 'element': 'S', 'x':...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Сероводород,H2S,0.45440,43.4,34.080000,5.098625,"((H, 2.0), (S, 1.0))",402,"['S', 'H', 'H']","[{'aid': 1, 'number': 16, 'element': 'S', 'x':...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Углекислый газ,CO2,0.36580,42.9,44.009000,3.784576,"((C, 1.0), (O, 2.0))",280,"['O', 'O', 'C']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Фтор,F2,0.11710,29.0,37.996806,1.551469,"((F, 2.0),)",24524,"['F', 'F']","[{'aid': 1, 'number': 9, 'element': 'F', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Фтороводород,HF,0.95650,73.9,20.006400,0.900523,"((F, 1.0), (H, 1.0))",14917,"['F', 'H']","[{'aid': 1, 'number': 9, 'element': 'F', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Хлор,Cl2,0.63430,54.2,70.900000,8.890355,"((Cl, 2.0),)",24526,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Хлороводород,HCl,0.37000,40.6,36.460000,4.569966,"((Cl, 1.0), (H, 1.0))",313,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Циановодород,HCN,1.12900,88.1,27.025000,3.000058,"((C, 1.0), (H, 1.0), (N, 1.0))",768,"['N', 'C', 'H']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Этан,C2H6,0.55800,65.1,30.070000,3.500840,"((C, 2.0), (H, 6.0))",6324,"['C', 'C', 'H', 'H', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Этилен,C2H4,0.46120,58.2,28.050000,3.251264,"((C, 2.0), (H, 4.0))",6325,"['C', 'C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
vdv_consts_rich.dropna(axis=1)

,Substance,Formula,Const_a,Const_b,Mol_weight,Volume,Parsed_Formula,cid,elements,atoms,...,cactvs_fingerprint,heavy_atom_count,isotope_atom_count,atom_stereo_count,defined_atom_stereo_count,undefined_atom_stereo_count,bond_stereo_count,defined_bond_stereo_count,undefined_bond_stereo_count,covalent_unit_count
0,Азот,N2,0.13700,38.7,28.014000,2.998428,"((N, 2.0),)",947,"['N', 'N']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...",...,0000000000000011000000000000000000000000000000...,2,0,0,0,0,0,0,0,1
1,Аммиак,NH3,0.42250,37.1,17.031000,1.873579,"((H, 3.0), (N, 1.0))",222,"['N', 'H', 'H', 'H']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...",...,0000000000000010000000000000000000000000000000...,1,0,0,0,0,0,0,0,1
2,Аргон,Ar,0.13550,32.0,39.900000,4.988916,"((Ar, 1.0),)",23968,['Ar'],"[{'aid': 1, 'number': 18, 'element': 'Ar', 'x'...",...,0000000000000000000000000000000000000000000000...,1,0,0,0,0,0,0,0,1
3,Ацетилен,C2H2,0.45160,52.2,26.040000,3.001687,"((C, 2.0), (H, 2.0))",6326,"['C', 'C', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,0000000001000000000000000000000000000000000000...,2,0,0,0,0,0,0,0,1
4,Бром,Br2,0.97500,59.1,159.810000,14.476459,"((Br, 2.0),)",24408,"['Br', 'Br']","[{'aid': 1, 'number': 35, 'element': 'Br', 'x'...",...,0000000000000000000000000000000000000000000110...,2,0,0,0,0,0,0,0,1
5,Бромоводород,HBr,0.45000,44.2,80.910000,7.363018,"((Br, 1.0), (H, 1.0))",260,"['Br', 'H']","[{'aid': 1, 'number': 35, 'element': 'Br', 'x'...",...,0000000000000000000000000000000000000000000100...,1,0,0,0,0,0,0,0,1
6,Бутан,C4H10,1.38900,116.4,58.120000,6.752104,"((C, 4.0), (H, 10.0))",7843,"['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', ...","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,1100000001100000000000000000000000000000000000...,4,0,0,0,0,0,0,0,1
7,Вода,H2O,0.55370,30.5,18.015000,1.453837,"((H, 2.0), (O, 1.0))",962,"['O', 'H', 'H']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,0000000000000000001000000000000000000000000000...,1,0,0,0,0,0,0,0,1
8,Водород,H2,0.02452,26.5,2.016000,0.249576,"((H, 2.0),)",783,"['H', 'H']","[{'aid': 1, 'number': 1, 'element': 'H', 'x': ...",...,0000000000000000000000000000000000000000000000...,0,0,0,0,0,0,0,0,1
9,Гексафторид серы,SF6,0.78570,87.9,146.060000,9.503456,"((F, 6.0), (S, 1.0))",17358,"['S', 'F', 'F', 'F', 'F', 'F', 'F']","[{'aid': 1, 'number': 16, 'element': 'S', 'x':...",...,0000000000000000000000011100000001000000000000...,7,0,0,0,0,0,0,0,1
10,Гелий,He,0.00346,23.8,4.002600,0.091952,"((He, 1.0),)",23987,['He'],"[{'aid': 1, 'number': 2, 'element': 'He', 'x':...",...,0000000000000000000000000000000000000000000000...,1,0,0,0,0,0,0,0,1
11,Гидразин,N2H4,0.84600,46.2,32.046000,3.497581,"((H, 4.0), (N, 2.0))",9321,"['N', 'N', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...",...,1000000000000011000000000000000000000000000000...,2,0,0,0,0,0,0,0,1
12,Кислород,O2,0.13820,31.9,31.999000,2.408521,"((O, 2.0),)",977,"['O', 'O']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,0000000000000000001100000000000000000000000000...,2,0,0,0,0,0,0,0,1
13,Криптон,Kr,0.51930,10.6,83.800000,6.538266,"((Kr, 1.0),)",66380,['Kr'],"[{'aid': 1, 'number': 36, 'element': 'Kr', 'x'...",...,0000000000000000000000000000000000000000000000...,1,1,0,0,0,0,0,0,1
14,Ксенон,Xe,0.41920,51.6,131.290000,11.494040,"((Xe, 1.0),)",23991,['Xe'],"[{'aid': 1, 'number': 54, 'element': 'Xe', 'x'...",...,0000000000000000000000000000000000000000000000...,1,0,0,0,0,0,0,0,1
15,Метан,CH4,0.23030,43.1,16.043000,1.875208,"((C, 1.0), (H, 4.0))",297,"['C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,1000000000000000000000000000000000000000000000...,1,0,0,0,0,0,0,0,1
16,Неон,Ne,0.02080,16.7,20.180000,0.817283,"((Ne, 1.0),)",23935,['Ne'],"[{'aid': 1, 'number': 10, 'element': 'Ne', 'x'...",...,0000000000000000000000000000000000000000000000...,1,0,0,0,0,0,0,0,1
17,Озон,O3,0.35700,48.7,47.998000,3.612781,"((O, 3.0),)",24823,"['O', 'O', 'O']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,0000000000000000001100000000000000000000000000...,3,0,0,0,0,0,0,0,1
18,Окись углерода,CO,0.14720,39.5,28.010000,2.580316,"((C, 1.0), (O, 1.0))",281,"['O', 'C']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,0000000000000000001000000000000000000000000000...,2,0,0,0,0,0,0,0,1
19,Пропан,C3H8,0.93900,90.5,44.100000,5.126472,"((C, 3.0), (H, 8.0))",6334,"['C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', ...","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,1100000001000000000000000000000000000000000000...,3,0,0,0,0,0,0,0,1
20,Сернистый ангидрид,SO2,0.68650,56.8,64.070000,7.257569,"((O, 2.0), (S, 1.0))",1119,"['S', 'O', 'O']","[{'aid': 1, 'number': 16, 'element': 'S', 'x':...",...,0000000000000000001100000000000001000000000000...,3,0,0,0,0,0,0,0,1
21,Сероводород,H2S,0.45440,43.4,34.080000,5.098625,"((H, 2.0), (S, 1.0))",402,"['S', 'H', 'H']","[{'aid': 1, 'number': 16, 'element': 'S', 'x':...",...,0000000000000000000000000000000001000000000000...,1,0,0,0,0,0,0,0,1
22,Углекислый газ,CO2,0.36580,42.9,44.009000,3.784576,"((C, 1.0), (O, 2.0))",280,"['O', 'O', 'C']","[{'aid': 1, 'number': 8, 'element': 'O', 'x': ...",...,0000000000000000001100000000000000000000000000...,3,0,0,0,0,0,0,0,1
23,Фтор,F2,0.11710,29.0,37.996806,1.551469,"((F, 2.0),)",24524,"['F', 'F']","[{'aid': 1, 'number': 9, 'element': 'F', 'x': ...",...,0000000000000000000000011000000000000000000000...,2,0,0,0,0,0,0,0,1
24,Фтороводород,HF,0.95650,73.9,20.006400,0.900523,"((F, 1.0), (H, 1.0))",14917,"['F', 'H']","[{'aid': 1, 'number': 9, 'element': 'F', 'x': ...",...,0000000000000000000000010000000000000000000000...,1,0,0,0,0,0,0,0,1
25,Хлор,Cl2,0.63430,54.2,70.900000,8.890355,"((Cl, 2.0),)",24526,"['Cl', 'Cl']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",...,0000000000000000000000000000000000000110000000...,2,0,0,0,0,0,0,0,1
26,Хлороводород,HCl,0.37000,40.6,36.460000,4.569966,"((Cl, 1.0), (H, 1.0))",313,"['Cl', 'H']","[{'aid': 1, 'number': 17, 'element': 'Cl', 'x'...",...,0000000000000000000000000000000000000100000000...,1,0,0,0,0,0,0,0,1
27,Циановодород,HCN,1.12900,88.1,27.025000,3.000058,"((C, 1.0), (H, 1.0), (N, 1.0))",768,"['N', 'C', 'H']","[{'aid': 1, 'number': 7, 'element': 'N', 'x': ...",...,0000000000000010000000000000000000000000000000...,2,0,0,0,0,0,0,0,1
28,Этан,C2H6,0.55800,65.1,30.070000,3.500840,"((C, 2.0), (H, 6.0))",6324,"['C', 'C', 'H', 'H', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,1000000001000000000000000000000000000000000000...,2,0,0,0,0,0,0,0,1
29,Этилен,C2H4,0.46120,58.2,28.050000,3.251264,"((C, 2.0), (H, 4.0))",6325,"['C', 'C', 'H', 'H', 'H', 'H']","[{'aid': 1, 'number': 6, 'element': 'C', 'x': ...",...,1000000001000000000000000000000000000000000000...,2,0,0,0,0,0,0,0,1